# Generated by Django 2.1.7 on 2019-03-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(help_text="Enter the book's natural language (e.g. Korea, English, French, etc.)", max_length=200),
        ),
    ]
